# build react app
FROM node:16 as build-stage
WORKDIR /app
COPY . .
RUN npm cache clean --force
RUN npm install
RUN npm run build


FROM nginx:1.15

COPY --from=build-stage /app/build /usr/share/nginx/html
COPY --from=build-stage /app/nginx/nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
