version: '3.7'

services:
  client:
    build:
      context: './client/'
    ports: 
      - 3000:3000
    volumes:
      - ./client:/app
  server:
    build:
      context: './server/'
    environment:
      - SERVER_PORT
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
    volumes:
      - ./server:/app
  db:
    build:
      context: './db/'
    environment:
      - DB_URI
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - DB_PORT
    ports:
      - ${DB_PORT}:${DB_PORT}
    volumes:
      - ./db:/app