version: '3.7'

services:
  client:
    build:
      context: './client/'
    ports: 
      - "3000:3000"
    volumes:
      - ./client:/app
  server:
    build:
      context: './server/'
    ports: 
      - "5000:5000"
    volumes:
      - ./server:/app