"""attempted uid datatype adjustment

Revision ID: 159af10805f0
Revises: b14b80e917d8
Create Date: 2022-10-30 22:35:11.877228

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '159af10805f0'
down_revision = 'b14b80e917d8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
