"""added cascade delete for collection

Revision ID: 365fa87005df
Revises: d7f93bc2d6b9
Create Date: 2022-12-24 08:39:44.109682

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '365fa87005df'
down_revision = 'd7f93bc2d6b9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
