"""updated key maps

Revision ID: 516fd324773a
Revises: 
Create Date: 2022-12-01 01:19:08.044834

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '516fd324773a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('collections',
    sa.Column('collection_id', sa.String(length=64), nullable=False),
    sa.Column('collection_name', sa.String(length=50), nullable=True),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('is_public', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('collection_id'),
    sa.UniqueConstraint('collection_id')
    )
    op.create_table('users',
    sa.Column('uid', sa.String(length=64), nullable=False),
    sa.Column('username', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('password', sa.String(length=100), nullable=True),
    sa.Column('created_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('username'),
    sa.UniqueConstraint('uid'),
    sa.UniqueConstraint('username')
    )
    op.create_table('user_collection_map',
    sa.Column('map_id', sa.String(length=64), nullable=False),
    sa.Column('collection_id', sa.String(length=64), nullable=True),
    sa.Column('user_id', sa.String(length=64), nullable=True),
    sa.Column('permission', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['collection_id'], ['collections.collection_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.uid'], ),
    sa.PrimaryKeyConstraint('map_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_collection_map')
    op.drop_table('users')
    op.drop_table('collections')
    # ### end Alembic commands ###
