"""added link table

Revision ID: 519c6f5a5f2f
Revises: 2da2c080d759
Create Date: 2022-12-21 02:54:24.649495

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '519c6f5a5f2f'
down_revision = '2da2c080d759'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('links',
    sa.Column('link_id', sa.String(length=64), nullable=False),
    sa.Column('link_name', sa.String(length=100), nullable=True),
    sa.Column('link_description', sa.String(length=500), nullable=True),
    sa.Column('link_url', sa.String(length=2048), nullable=True),
    sa.Column('collection_id', sa.String(length=64), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['collection_id'], ['collections.collection_id'], ),
    sa.PrimaryKeyConstraint('link_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('links')
    # ### end Alembic commands ###
