"""updated uid datatype

Revision ID: 766479206723
Revises: 8c1501e2bf6a
Create Date: 2022-10-30 22:07:26.805193

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '766479206723'
down_revision = '8c1501e2bf6a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
