"""removed email as primary key

Revision ID: bfa0d219a2f7
Revises: 4496dfebcf43
Create Date: 2022-11-12 07:19:48.257444

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bfa0d219a2f7'
down_revision = '4496dfebcf43'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
