"""added last updated by column to links table

Revision ID: d7f93bc2d6b9
Revises: 519c6f5a5f2f
Create Date: 2022-12-23 06:11:24.456572

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd7f93bc2d6b9'
down_revision = '519c6f5a5f2f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('links', sa.Column('last_updated_by', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('links', 'last_updated_by')
    # ### end Alembic commands ###
